FROM guangie88/hdfs-client:onbuild AS original

FROM guangie88/hdfs-client:krb5-onbuild AS krb5

FROM guangie88/hdfs-client:aws-onbuild AS aws

FROM guangie88/hdfs-client:aws-krb5-onbuild AS aws-krb5
