FROM guangie88/hdfs-client-onbuild:latest AS hdfs-client

FROM guangie88/hdfs-client-krb5-onbuild:latest AS hdfs-client-krb5

FROM guangie88/hdfs-client-aws-onbuild:latest AS hdfs-client-aws

FROM guangie88/hdfs-client-krb5-aws-onbuild:latest AS hdfs-client-krb5-aws
